---
- name: Waiting for SSH connection
  hosts: ansible
  gather_facts: no
  tasks:
    - name: Waiting for SSH connection!
      wait_for:
        port: 22
        host: '{{ inventory_hostname }}'
        delay: 5
      delegate_to: localhost

- name: Set up the application
  hosts: ansible

  tasks:
  - name: Create folder for the app instance
    file:
      path: /tmp/app-instance/
      state: directory
      mode: '0755'

  - name: Synch app-instance folder to remote server
    synchronize:
      mode: push
      src: app-instance/
      dest: /tmp/app-instance/

  - name: Docker compose up!
    docker_compose:
      project_src: /tmp/app-instance/
    register: output
